--[[
DO NOT MODITY!  Auto generated by py_exceltools

skill.xlsx base
]]


return
{
    [10000] = {['id'] = 10000},
    [11000] = {['id'] = 11000},
    [12000] = {['id'] = 12000},
    [13000] = {['id'] = 13000},
    [14000] = {['id'] = 14000}
}