--[[
DO NOT MODITY!  Auto generated by py_exceltools

ai.xlsx base
]]


return
{
    [1] =
    {
        ['id'] = 1,
        ['isReturn'] = 0,
        ['maxDist'] = 10000,
        ['param'] = {['login_time'] = 600,['logout_time'] = 1200},
        ['type'] = 1
    },
    [10001] = {['id'] = 10001,['isReturn'] = 1,['maxDist'] = 20,['type'] = 2},
    [20000] = {['id'] = 20000,['isReturn'] = 1,['maxDist'] = 30,['type'] = 3},
    [20001] = {['id'] = 20001,['isReturn'] = 1,['maxDist'] = 40,['type'] = 2}
}