--[[
DO NOT MODITY!  Auto generated by py_exceltools

attribute.xlsx base
]]


return
{
    [1] = {['factor'] = 0,['id'] = 1,['name'] = '血量'},
    [2] = {['factor'] = 2.5,['id'] = 2,['name'] = '最大血量'},
    [3] = {['factor'] = 8,['id'] = 3,['name'] = '攻击'},
    [4] = {['factor'] = 8,['id'] = 4,['name'] = '防御'}
}