--[[ Generated by PyExcelTool. DO NOT MODIFY. ]]
---@class conf.ai_base_conf
---@field id integer @index 唯一id
---@field isReturn integer 是否返回出生点
---@field maxDist integer 离开出生点距离
---@field param table<string, integer> 其他AI参数
---@field type integer AI类型
---@class conf.attr_base_conf
---@field id integer @index 属性类型
---@field factor number 战力系数
---@field name string 属性名字
---@class conf.area_conf
---@field id integer @index 区域属性id
---@field max_x integer 区域右下角x
---@field max_y integer 区域右下角y
---@field min_x integer 区域左上角x
---@field min_y integer 区域左上角y
---@field param integer[] 区域属性参数
---@field type integer 区域属性类型
---@class conf.base_conf
---@field id integer @index 副本id
---@field scene integer[] 场景列表
---@class conf.refresh_conf
---@field id integer @index 刷怪配置id
---@field count integer 刷怪数量
---@field max_x integer 刷怪右下角x
---@field max_y integer 刷怪右下角y
---@field min_x integer 刷怪左上角x
---@field min_y integer 刷怪左上角y
---@class conf.scene_conf
---@field id integer @index 场景id
---@field area integer[] 区域属性
---@field born_x integer 出生点x像素
---@field born_y integer 出生点y像素
---@field map integer 地图数据id
---@field refresh integer[] 自动刷怪配置
---@class conf.equip_weapon_conf
---@field id integer @index 唯一id
---@field attack integer 攻击力
---@field attackSpeed integer 攻击速度
---@field crit number 暴击
---@field defense integer 防御
---@field desc string 描述
---@field hp integer 血量
---@field iconId string 图标
---@field moveSpeed integer 移动速度
---@field mp integer 魔法值
---@field name string 名字
---@class conf.item_conf
---@field id integer @index 唯一id
---@field bag_id integer 背包类型id
---@field desc string 描述
---@field iconId integer 图标
---@field name string 名字
---@field pile integer 最大可堆叠数量
---@field sell integer 出售价格
---@field type integer 类型
---@class conf.mail_conf
---@field id integer @index 唯一id
---@field text string 内容
---@field title string 标题
---@field type integer 类型
---@class conf.hero_conf
---@field id integer @index 英雄id
---@field agility integer 敏捷
---@field asset_id string 资源id
---@field attack integer 攻击力
---@field attack_range integer 攻击范围
---@field attack_speed integer 攻击速度
---@field crit integer 暴击
---@field crit_damage integer 暴击伤害
---@field death_sound string 死亡音效
---@field defense integer 防御力
---@field exp integer 掉落经验
---@field hit_effect_bone string 攻击特效
---@field hit_sound string 攻击音效
---@field hp integer 血量
---@field intelligence integer 智力
---@field level integer 等级
---@field move_speed integer 移动速度
---@field mp integer 法力值
---@field name string 名字
---@field prime_attribute string 天赋属性
---@field scale_ratio number
---@field skill integer[] 技能
---@field strength integer 力量
---@field upgrade_id integer 升级后英雄id
---@class conf.levelup_conf
---@field attr integer[][] 等级属性
---@field bagGrid integer 背包空格
---@field level integer 等级
---@class conf.welcome_conf
---@field attachment integer[][] 新手邮件附件
---@field mail_ctx string 邮件内容
---@field resources integer[][] 新手道具

---@class conf
---@field ai_base_conf table<integer, conf.ai_base_conf>
---@field attr_base_conf table<integer, conf.attr_base_conf>
---@field dungeon_area_conf table<integer, conf.area_conf>
---@field dungeon_base_conf table<integer, conf.base_conf>
---@field dungeon_refresh_conf table<integer, conf.refresh_conf>
---@field dungeon_scene_conf table<integer, conf.scene_conf>
---@field equip_weapon_conf table<integer, conf.equip_weapon_conf>
---@field item_conf table<integer, conf.item_conf>
---@field mail_conf table<integer, conf.mail_conf>
---@field player_hero_conf table<integer, conf.hero_conf>
---@field player_levelup_conf conf.levelup_conf[]
---@field player_welcome_conf conf.welcome_conf
local conf = {}
local _cache = {}
conf.conf_path = "./"

function conf.load_ai_base_conf()
    if _cache.ai_base_conf then return _cache.ai_base_conf end
    _cache.ai_base_conf = dofile(conf.conf_path .. "ai_base_conf.lua")
    conf.ai_base_conf = _cache.ai_base_conf
    return _cache.ai_base_conf
end

function conf.load_attr_base_conf()
    if _cache.attr_base_conf then return _cache.attr_base_conf end
    _cache.attr_base_conf = dofile(conf.conf_path .. "attr_base_conf.lua")
    conf.attr_base_conf = _cache.attr_base_conf
    return _cache.attr_base_conf
end

function conf.load_dungeon_area_conf()
    if _cache.dungeon_area_conf then return _cache.dungeon_area_conf end
    _cache.dungeon_area_conf = dofile(conf.conf_path .. "dungeon/area_conf.lua")
    conf.dungeon_area_conf = _cache.dungeon_area_conf
    return _cache.dungeon_area_conf
end

function conf.load_dungeon_base_conf()
    if _cache.dungeon_base_conf then return _cache.dungeon_base_conf end
    _cache.dungeon_base_conf = dofile(conf.conf_path .. "dungeon/base_conf.lua")
    conf.dungeon_base_conf = _cache.dungeon_base_conf
    return _cache.dungeon_base_conf
end

function conf.load_dungeon_refresh_conf()
    if _cache.dungeon_refresh_conf then return _cache.dungeon_refresh_conf end
    _cache.dungeon_refresh_conf = dofile(conf.conf_path .. "dungeon/refresh_conf.lua")
    conf.dungeon_refresh_conf = _cache.dungeon_refresh_conf
    return _cache.dungeon_refresh_conf
end

function conf.load_dungeon_scene_conf()
    if _cache.dungeon_scene_conf then return _cache.dungeon_scene_conf end
    _cache.dungeon_scene_conf = dofile(conf.conf_path .. "dungeon/scene_conf.lua")
    conf.dungeon_scene_conf = _cache.dungeon_scene_conf
    return _cache.dungeon_scene_conf
end

function conf.load_equip_weapon_conf()
    if _cache.equip_weapon_conf then return _cache.equip_weapon_conf end
    _cache.equip_weapon_conf = dofile(conf.conf_path .. "equip_weapon_conf.lua")
    conf.equip_weapon_conf = _cache.equip_weapon_conf
    return _cache.equip_weapon_conf
end

function conf.load_item_conf()
    if _cache.item_conf then return _cache.item_conf end
    _cache.item_conf = dofile(conf.conf_path .. "item_conf.lua")
    conf.item_conf = _cache.item_conf
    return _cache.item_conf
end

function conf.load_mail_conf()
    if _cache.mail_conf then return _cache.mail_conf end
    _cache.mail_conf = dofile(conf.conf_path .. "mail_conf.lua")
    conf.mail_conf = _cache.mail_conf
    return _cache.mail_conf
end

function conf.load_player_hero_conf()
    if _cache.player_hero_conf then return _cache.player_hero_conf end
    _cache.player_hero_conf = dofile(conf.conf_path .. "player/hero_conf.lua")
    conf.player_hero_conf = _cache.player_hero_conf
    return _cache.player_hero_conf
end

function conf.load_player_levelup_conf()
    if _cache.player_levelup_conf then return _cache.player_levelup_conf end
    _cache.player_levelup_conf = dofile(conf.conf_path .. "player/levelup_conf.lua")
    conf.player_levelup_conf = _cache.player_levelup_conf
    return _cache.player_levelup_conf
end

function conf.load_player_welcome_conf()
    if _cache.player_welcome_conf then return _cache.player_welcome_conf end
    _cache.player_welcome_conf = dofile(conf.conf_path .. "player/welcome_conf.lua")
    conf.player_welcome_conf = _cache.player_welcome_conf
    return _cache.player_welcome_conf
end

function conf.reload_all()
    _cache.ai_base_conf = nil
    conf.ai_base_conf = nil
    package.loaded["ai_base_conf"] = nil
    _cache.attr_base_conf = nil
    conf.attr_base_conf = nil
    package.loaded["attr_base_conf"] = nil
    _cache.dungeon_area_conf = nil
    conf.dungeon_area_conf = nil
    package.loaded["dungeon/area_conf"] = nil
    _cache.dungeon_base_conf = nil
    conf.dungeon_base_conf = nil
    package.loaded["dungeon/base_conf"] = nil
    _cache.dungeon_refresh_conf = nil
    conf.dungeon_refresh_conf = nil
    package.loaded["dungeon/refresh_conf"] = nil
    _cache.dungeon_scene_conf = nil
    conf.dungeon_scene_conf = nil
    package.loaded["dungeon/scene_conf"] = nil
    _cache.equip_weapon_conf = nil
    conf.equip_weapon_conf = nil
    package.loaded["equip_weapon_conf"] = nil
    _cache.item_conf = nil
    conf.item_conf = nil
    package.loaded["item_conf"] = nil
    _cache.mail_conf = nil
    conf.mail_conf = nil
    package.loaded["mail_conf"] = nil
    _cache.player_hero_conf = nil
    conf.player_hero_conf = nil
    package.loaded["player/hero_conf"] = nil
    _cache.player_levelup_conf = nil
    conf.player_levelup_conf = nil
    package.loaded["player/levelup_conf"] = nil
    _cache.player_welcome_conf = nil
    conf.player_welcome_conf = nil
    package.loaded["player/welcome_conf"] = nil
end

return conf

