--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from dungeon_area
]]


return
{
    {['id'] = 1},{['id'] = 2},{['id'] = 3},{['id'] = 4},
    {['id'] = 5},{['id'] = 6},{['id'] = 7},{['id'] = 8},
    {['id'] = 9},{['id'] = 10}
}