--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from equip_weapon
]]


return
{
    {
        ['attack'] = 100,
        ['attackSpeed'] = 0,
        ['crit'] = 0.01,
        ['defense'] = 0,
        ['desc'] = '这是一把短剑',
        ['hp'] = 0,
        ['iconId'] = 21000,
        ['id'] = 10000,
        ['moveSpeed'] = 0,
        ['mp'] = 0,
        ['name'] = '短剑'
    },
    {
        ['attack'] = 300,
        ['attackSpeed'] = 0,
        ['crit'] = 0.02,
        ['defense'] = 0,
        ['desc'] = '这是一把长剑',
        ['hp'] = 0,
        ['iconId'] = 21001,
        ['id'] = 10001,
        ['moveSpeed'] = 0,
        ['mp'] = 0,
        ['name'] = '长剑'
    }
}