--[[
DO NOT MODITY!  Auto generated by py_exceltools

item.xlsx item
]]


return
{
    [1] =
    {
        ['desc'] = '金币',
        ['iconId'] = 1,
        ['id'] = 1,
        ['name'] = '金币',
        ['type'] = 1
    },
    [2] =
    {
        ['desc'] = '元宝',
        ['iconId'] = 2,
        ['id'] = 2,
        ['name'] = '元宝',
        ['type'] = 2
    },
    [3] =
    {
        ['desc'] = '经验',
        ['iconId'] = 3,
        ['id'] = 3,
        ['name'] = '经验',
        ['type'] = 3
    },
    [10000] =
    {
        ['bag_id'] = 1,
        ['desc'] = '这是一把短剑',
        ['iconId'] = 10000,
        ['id'] = 10000,
        ['name'] = '短剑',
        ['pile'] = 1,
        ['sell'] = 55,
        ['type'] = 1000
    },
    [10001] =
    {
        ['bag_id'] = 1,
        ['desc'] = '这是一把长剑',
        ['iconId'] = 10001,
        ['id'] = 10001,
        ['name'] = '长剑',
        ['pile'] = 1,
        ['sell'] = 85,
        ['type'] = 1000
    },
    [20000] =
    {
        ['bag_id'] = 1,
        ['desc'] = '恢复少量hp',
        ['iconId'] = 20000,
        ['id'] = 20000,
        ['name'] = '小还丹',
        ['pile'] = 99,
        ['sell'] = 9,
        ['type'] = 1000
    },
    [20001] =
    {
        ['bag_id'] = 1,
        ['desc'] = '恢复大量hp',
        ['iconId'] = 20001,
        ['id'] = 20001,
        ['name'] = '大还丹',
        ['pile'] = 99,
        ['sell'] = 18,
        ['type'] = 1000
    }
}