--[[
DO NOT MODITY!  Auto generated by py_exceltools

Y-邮件.xlsx 邮件
]]


return
{
    [1] =
    {
        ['id'] = 1,
        ['text'] = '这是{0}未领取的奖励，通过邮件发送，请查收',
        ['title'] = '测试邮件',
        ['type'] = 1
    },
    [2] =
    {
        ['id'] = 2,
        ['text'] = '这是{0}未领取的奖励，通过邮件发送，请查收',
        ['title'] = '测试邮件',
        ['type'] = 1
    }
}