--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from player_hero
]]


return
{
    {
        ['agility'] = 8,
        ['asset_id'] = 'js',
        ['attack'] = 29,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['crit'] = 0,
        ['crit_damage'] = 0,
        ['defense'] = 1,
        ['exp'] = 400,
        ['hit_effect_bone'] = 'Bip01 Pelvis',
        ['hp'] = 650,
        ['id'] = 100000,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 400,
        ['mp'] = 0,
        ['name'] = '战士',
        ['prime_attribute'] = 'strength',
        ['scale_ratio'] = 1,
        ['skill'] = {10000,11000,12000,13000,14000},
        ['strength'] = 22,
        ['upgrade_id'] = 10000
    },
    {
        ['agility'] = 8,
        ['asset_id'] = '0_HM',
        ['attack'] = 14,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['crit'] = 0,
        ['crit_damage'] = 0,
        ['defense'] = 2,
        ['exp'] = 800,
        ['hit_effect_bone'] = 'Bone33',
        ['hp'] = 230,
        ['id'] = 100001,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 300,
        ['mp'] = 0,
        ['name'] = '法师',
        ['prime_attribute'] = 'agility',
        ['scale_ratio'] = 0.800000011921,
        ['strength'] = 15,
        ['upgrade_id'] = 0
    },
    {
        ['agility'] = 8,
        ['asset_id'] = '0_HM',
        ['attack'] = 8,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['crit'] = 0,
        ['crit_damage'] = 0,
        ['defense'] = 1,
        ['exp'] = 400,
        ['hit_effect_bone'] = 'Bone33',
        ['hp'] = 200,
        ['id'] = 100002,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 300,
        ['mp'] = 0,
        ['name'] = '射手',
        ['prime_attribute'] = 'agility',
        ['scale_ratio'] = 0.5,
        ['strength'] = 13,
        ['upgrade_id'] = 0
    }
}