--[[
DO NOT MODITY!  Auto generated by py_exceltools

player.xlsx welcome
]]


return
{
    ['attachment'] = {{1,999999},{10000,1},{20000,99},{20001,99}},
    ['mail_ctx'] = '测试新手邮件',
    ['resources'] = {{1,999999},{10000,1},{20000,99},{20001,99}}
}