--[[
DO NOT MODITY!  Auto generated by py_exceltools

player.xlsx welcome
]]


return
{
    ['attachment'] =
    {
        {['count'] = 999999,['id'] = 0,['res'] = 1},
        {['count'] = 1,['id'] = 10000,['res'] = 3},
        {['count'] = 99,['id'] = 20000,['res'] = 3},
        {['count'] = 99,['id'] = 20001,['res'] = 3}
    },
    ['mail_ctx'] = '测试新手邮件',
    ['resources'] =
    {
        {['count'] = 999999,['id'] = 0,['res'] = 1},
        {['count'] = 1,['id'] = 10000,['res'] = 3},
        {['count'] = 99,['id'] = 20000,['res'] = 3},
        {['count'] = 99,['id'] = 20001,['res'] = 3}
    }
}