--[[
DO NOT MODITY!  Auto generated by py_exceltools

dungeon.xlsx area
]]


return
{
    [1] = {['id'] = 1},
    [2] = {['id'] = 2},
    [3] = {['id'] = 3},
    [4] = {['id'] = 4},
    [5] = {['id'] = 5},
    [6] = {['id'] = 6},
    [7] = {['id'] = 7},
    [8] = {['id'] = 8},
    [9] = {['id'] = 9},
    [10] = {['id'] = 10}
}