--[[
DO NOT MODITY!  Auto generated by py_exceltools

dungeon.xlsx base
]]


return
{
    [0] = {['id'] = 0,['scene'] = {1,2,3,4,5,6,7,8,9,10}},
    [1] = {['id'] = 1,['scene'] = {1}},
    [2] = {['id'] = 2,['scene'] = {2}},
    [3] = {['id'] = 3,['scene'] = {3}},
    [4] = {['id'] = 4,['scene'] = {4}},
    [5] = {['id'] = 5,['scene'] = {5}},
    [6] = {['id'] = 6,['scene'] = {6}},
    [7] = {['id'] = 7,['scene'] = {7}},
    [8] = {['id'] = 8,['scene'] = {8}},
    [9] = {['id'] = 9,['scene'] = {9}},
    [10] = {['id'] = 10,['scene'] = {10}}
}