--[[
DO NOT MODITY!  Auto generated by py_exceltools

dungeon.xlsx refresh
]]


return
{
    [1] =
    {
        ['count'] = 50,
        ['id'] = 1,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [2] =
    {
        ['count'] = 50,
        ['id'] = 2,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [3] =
    {
        ['count'] = 50,
        ['id'] = 3,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [4] =
    {
        ['count'] = 50,
        ['id'] = 4,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [5] =
    {
        ['count'] = 50,
        ['id'] = 5,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [6] =
    {
        ['count'] = 50,
        ['id'] = 6,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [7] =
    {
        ['count'] = 50,
        ['id'] = 7,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [8] =
    {
        ['count'] = 50,
        ['id'] = 8,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [9] =
    {
        ['count'] = 50,
        ['id'] = 9,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    },
    [10] =
    {
        ['count'] = 50,
        ['id'] = 10,
        ['max_x'] = 64,
        ['max_y'] = 128,
        ['min_x'] = 0,
        ['min_y'] = 0
    }
}