--[[
DO NOT MODITY!  Auto generated by py_exceltools

dungeon.xlsx scene
]]


return
{
    [1] =
    {
        ['area'] = {1},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 1,
        ['map'] = 1,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [2] =
    {
        ['area'] = {2},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 2,
        ['map'] = 2,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [3] =
    {
        ['area'] = {3},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 3,
        ['map'] = 3,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [4] =
    {
        ['area'] = {4},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 4,
        ['map'] = 4,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [5] =
    {
        ['area'] = {5},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 5,
        ['map'] = 5,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [6] =
    {
        ['area'] = {6},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 6,
        ['map'] = 6,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [7] =
    {
        ['area'] = {7},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 7,
        ['map'] = 7,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [8] =
    {
        ['area'] = {8},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 8,
        ['map'] = 8,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [9] =
    {
        ['area'] = {9},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 9,
        ['map'] = 9,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    [10] =
    {
        ['area'] = {10},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 10,
        ['map'] = 10,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    }
}