--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from ai_base
]]


return
{
    {
        ['id'] = 1,
        ['isReturn'] = 0,
        ['maxDist'] = 10000,
        ['param'] = {['login_time'] = 30,['logout_time'] = 30},
        ['type'] = 1
    },
    {['id'] = 10001,['isReturn'] = 1,['maxDist'] = 20,['type'] = 2},
    {['id'] = 20000,['isReturn'] = 1,['maxDist'] = 30,['type'] = 3},
    {['id'] = 20001,['isReturn'] = 1,['maxDist'] = 40,['type'] = 2}
}