--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from dungeon_refresh
]]


return
{
    {['count'] = 50,['id'] = 1,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 2,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 3,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 4,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 5,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 6,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 7,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 8,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 9,['max_x'] = 64,['max_y'] = 128},
    {['count'] = 50,['id'] = 10,['max_x'] = 64,['max_y'] = 128}
}