--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from dungeon_base
]]


return
{
    {['id'] = 0,['scene'] = {1,2,3,4,5,6,7,8,9,10}},
    {['id'] = 1,['scene'] = {1}},{['id'] = 2,['scene'] = {2}},
    {['id'] = 3,['scene'] = {3}},{['id'] = 4,['scene'] = {4}},
    {['id'] = 5,['scene'] = {5}},{['id'] = 6,['scene'] = {6}},
    {['id'] = 7,['scene'] = {7}},{['id'] = 8,['scene'] = {8}},
    {['id'] = 9,['scene'] = {9}},{['id'] = 10,['scene'] = {10}}
}