--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from dungeon_scene
]]


return
{
    {
        ['area'] = {1},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 1,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {2},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 2,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {3},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 3,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {4},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 4,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {5},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 5,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {6},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 6,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {7},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 7,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {8},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 8,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {9},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 9,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    },
    {
        ['area'] = {10},
        ['born_x'] = 64,
        ['born_y'] = 32,
        ['id'] = 10,
        ['refresh'] = {1,2,3,4,5,6,7,8}
    }
}