--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/
]]

return
{
    {
        ['id'] = 10000,
        ['desc'] = '这是一把短剑',
        ['iconId'] = 10000,
        ['name'] = '短剑',
        ['pile'] = 1,
        ['sell'] = 55,
    },
    {
        ['id'] = 10001,
        ['desc'] = '这是一把长剑',
        ['iconId'] = 10001,
        ['name'] = '长剑',
        ['pile'] = 1,
        ['sell'] = 85,
    },
    {
        ['id'] = 20000,
        ['desc'] = '恢复少量hp',
        ['iconId'] = 20000,
        ['name'] = '小还丹',
        ['pile'] = 99,
        ['sell'] = 9,
    },
    {
        ['id'] = 20001,
        ['desc'] = '恢复大量hp',
        ['iconId'] = 20001,
        ['name'] = '大还丹',
        ['pile'] = 99,
        ['sell'] = 18,
    },
}