--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from map_scene
]]


return
{
    {
        ['asset_id'] = 100001,
        ['id'] = 100000,
        ['min_map'] = 'pic1',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    },
    {
        ['asset_id'] = 100002,
        ['id'] = 100001,
        ['min_map'] = 'pic2',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    },
    {
        ['asset_id'] = 100001,
        ['id'] = 100002,
        ['min_map'] = 'pic3',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    },
    {
        ['asset_id'] = 100002,
        ['id'] = 100003,
        ['min_map'] = 'pic4',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    },
    {
        ['asset_id'] = 100001,
        ['id'] = 100004,
        ['min_map'] = 'pic5',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    },
    {
        ['asset_id'] = 100002,
        ['id'] = 100005,
        ['min_map'] = 'pic6',
        ['monster_wave'] = 100000,
        ['pos_x'] = 2628,
        ['pos_y'] = 9,
        ['pos_z'] = 1891
    }
}