--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/
]]

return
{
    {
        ['id'] = 100000,
        ['next_wave'] = 100001,
        ['monster_id'] = {200000,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100001,
        ['next_wave'] = 100002,
        ['monster_id'] = {200000,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100002,
        ['next_wave'] = 100003,
        ['monster_id'] = {200001,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100003,
        ['next_wave'] = 100004,
        ['monster_id'] = {200001,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100004,
        ['next_wave'] = 100005,
        ['monster_id'] = {200001,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100005,
        ['next_wave'] = 100006,
        ['monster_id'] = {200001,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100006,
        ['next_wave'] = 100007,
        ['monster_id'] = {200001,},
        ['monster_num'] = {2,},
    },
    {
        ['id'] = 100007,
        ['monster_id'] = {200000,200001,200002,},
        ['monster_num'] = {1,1,1,},
    },
}