--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from map_monster
]]


return
{
    {
        ['agility'] = 8,
        ['asset_id'] = '0_HM',
        ['attack'] = 8,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['defense'] = 1,
        ['exp'] = 400,
        ['hit_effect_bone'] = 'Bone33',
        ['hp'] = 200,
        ['id'] = 200000,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 300,
        ['name'] = '小小蛤蟆',
        ['prime_attribute'] = 'agility',
        ['scale_ratio'] = 0.5,
        ['strength'] = 13
    },
    {
        ['agility'] = 8,
        ['asset_id'] = '0_HM',
        ['attack'] = 14,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['defense'] = 2,
        ['exp'] = 800,
        ['hit_effect_bone'] = 'Bone33',
        ['hp'] = 230,
        ['id'] = 200001,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 300,
        ['name'] = '小蛤蟆',
        ['prime_attribute'] = 'agility',
        ['scale_ratio'] = 0.800000011921,
        ['strength'] = 15
    },
    {
        ['agility'] = 8,
        ['asset_id'] = '0_HM',
        ['attack'] = 8,
        ['attack_range'] = 500,
        ['attack_speed'] = 1,
        ['defense'] = 1,
        ['exp'] = 400,
        ['hit_effect_bone'] = 'Bone33',
        ['hp'] = 200,
        ['id'] = 200002,
        ['intelligence'] = 17,
        ['level'] = 1,
        ['move_speed'] = 300,
        ['name'] = '小小蛤蟆',
        ['prime_attribute'] = 'agility',
        ['scale_ratio'] = 0.5,
        ['strength'] = 13
    }
}