--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from player_welcome
]]


return
{
    ['attachment'] =
    {
        {['count'] = 999999,['id'] = 0,['res'] = 1},
        {['count'] = 1,['id'] = 10000,['res'] = 3},
        {['count'] = 99,['id'] = 20000,['res'] = 3},
        {['count'] = 99,['id'] = 20001,['res'] = 3}
    },
    ['mail_ctx'] = 1,
    ['resources'] =
    {
        {['count'] = 999999,['id'] = 0,['res'] = 1},
        {['count'] = 1,['id'] = 10000,['res'] = 3},
        {['count'] = 99,['id'] = 20000,['res'] = 3},
        {['count'] = 99,['id'] = 20001,['res'] = 3}
    }
}