--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/
]]

return
{
    {
        ['level'] = 1,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 2,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 3,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 4,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 5,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 6,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 7,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 8,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 9,
        ['bagGrid'] = 50,
    },
    {
        ['level'] = 10,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 11,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 12,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 13,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 14,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 15,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 16,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 17,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 18,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 19,
        ['bagGrid'] = 60,
    },
    {
        ['level'] = 20,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 21,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 22,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 23,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 24,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 25,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 26,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 27,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 28,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 29,
        ['bagGrid'] = 70,
    },
    {
        ['level'] = 30,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 31,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 32,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 33,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 34,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 35,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 36,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 37,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 38,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 39,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 40,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 41,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 42,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 43,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 44,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 45,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 46,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 47,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 48,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 49,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 50,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 51,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 52,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 53,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 54,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 55,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 56,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 57,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 58,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 59,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 60,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 61,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 62,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 63,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 64,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 65,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 66,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 67,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 68,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 69,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 70,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 71,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 72,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 73,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 74,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 75,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 76,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 77,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 78,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 79,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 80,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 81,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 82,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 83,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 84,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 85,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 86,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 87,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 88,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 89,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 90,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 91,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 92,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 93,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 94,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 95,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 96,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 97,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 98,
        ['bagGrid'] = 80,
    },
    {
        ['level'] = 99,
        ['bagGrid'] = 80,
    },
}