--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from skill_base
]]


return
{
    {['id'] = 10000},{['id'] = 11000},{['id'] = 12000},
    {['id'] = 13000},{['id'] = 14000}
}